# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gratitude' do
  pod 'AppCenter/Crashes', '~> 1.13.0'
  pod 'AppCenter/Analytics', '~> 1.13.0'
  pod 'AppCenterReactNativeShared', '~> 1.12.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Gratitude

  platform :ios, '9.0'
  # pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  # pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

  target 'GratitudeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Gratitude-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Gratitude-tvOS

  target 'Gratitude-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
