# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gratitute' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Gratitute
  pod 'AppCenter/Crashes', '~> 1.13.0'
  pod 'AppCenter/Analytics', '~> 1.13.0'
  pod 'AppCenterReactNativeShared', '~> 1.12.0'

  # Stripe
  pod 'Stripe', '~> 14.0.0'
  
  platform :ios, '9.0'

  target 'GratituteTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Gratitute-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Gratitute-tvOS

  target 'Gratitute-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
